name: ESFollowers
version: ${project.version}
main: org.enchantedskies.esfollowers.ESFollowers
api-version: 1.16
authors: [Dav_e_]
depend: [UserInterface]
softdepend: [Essentials]
commands:
  followers:
    description: Opens Follower GUI
    usage: /followers
  gethexarmor:
    description: Gives the user a colored piece of leather armor based on a hex value
    usage: /gethexarmor
permissions:
  follower.admin.reload:
    description: Allows you to reload the Followers plugin
    default: op
  follower.admin.create:
    description: Allows you to create followers using the follower creator stick
    default: op
  follower.admin.delete:
    description: Allows you to delete followers
    default: op
  follower.name:
    description: Allows you to name your Follower
    default: op