name: Followers
version: ${project.version}
main: me.dave.followers.Followers
api-version: 1.19
authors: [ Dav_e_ ]
depend: [ ProtocolLib ]
softdepend: [ Essentials, GSit, PlaceholderAPI, floodgate ]
commands:
  followers:
    description: Opens Follower GUI
    usage: /followers
    aliases: ["pets"]
  gethexarmor:
    description: Gives the user a colored piece of leather armor based on a hex value
    usage: /gethexarmor
  dye:
    description: Dyes a user's leather item
    usage: /dye
permissions:
  follower.admin.reload:
    description: Allows you to reload the Followers plugin
    default: op
  follower.admin.create:
    description: Allows you to create followers using the follower creator item
    default: op
  follower.admin.delete:
    description: Allows you to delete followers
    default: op
  follower.admin.dye:
    description: Allows you to get/dye armour
    default: op
  follower.name:
    description: Allows you to name your Follower
    default: op