name: ESFollowers
version: ${project.version}
main: org.enchantedskies.esfollowers.ESFollowers
api-version: 1.16
authors: [Dav_e_]
softdepend: [Essentials]
commands:
  followers:
    description: Opens Follower GUI
    usage: /followers
  gethexarmor:
    description: Gives the user a colored piece of leather armor based on a hex value
    usage: /gethexarmor