name: Followers
version: ${version}
main: org.lushplugins.followers.Followers
api-version: 1.16
authors:
  - OakLoaf
depend:
  - ProtocolLib
softdepend:
  - Essentials
  - floodgate
  - GSit
  - PlaceholderAPI
  - SimpleSit
commands:
  followers:
    description: Opens Follower GUI
    usage: /followers
    aliases:
      - "pets"
  gethexarmor:
    description: Gives the user a colored piece of leather armor based on a hex value
    usage: /gethexarmor
  dye:
    description: Dyes a user's leather item
    usage: /dye