name: ESFollowers
version: ${project.version}
main: org.enchantedskies.esfollowers.ESFollowers
api-version: 1.16
authors: [Dav_e_]
commands:
  follower:
    description: Opens follower GUI
    usage: /follower